<a href="https://colab.research.google.com/github/Sandrapm-5/ADBMS/blob/main/Exp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aim: To implement 

(a) Matrix operations (using vectorization), 

(b) transformation using python and 

(c) SVD using Python.

**Program**

(a) Matrix operations using vectorization

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the rank of the array; 
the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets. Numpy also provides many functions to create arrays with all zero values, all  ones, identity matrix, all random values.

Vectorization is used to speed up the Python code without using loop. Using such a function can help in minimizing the running time of code efficiently. Various operations are being performed over vector such as dot product of vectors which is also known as scalar product as it produces single output, outer products which results in square matrix of dimension equal to length X length of the vectors, Element wise multiplication which products the element of same indexes and dimension of the matrix remain unchanged.


In [1]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print("type: %s" %type(a))            # Prints "<class 'numpy.ndarray'>"
print("shape: %s" %a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print("\n shape of b:",b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

a = np.zeros((2,2))   # Create an array of all zeros
print("All zeros matrix:\n  %s" %a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print("\nAll ones matrix:\n  %s" %b)              # Prints "[[ 1.  1.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print("\n identity matrix: \n%s"%d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print("\n random matrix: \n%s"%e)

type: <class 'numpy.ndarray'>
shape: 3
1 2 3
[5 2 3]

 shape of b: (2, 3)
1 2 4
All zeros matrix:
  [[0. 0.]
 [0. 0.]]

All ones matrix:
  [[1. 1.]]

 identity matrix: 
[[1. 0.]
 [0. 1.]]

 random matrix: 
[[0.34891702 0.76887592]
 [0.19143942 0.1416376 ]]


In [6]:
import numpy as np

a=np.array([5, 6, 7])  
print("type: %s" %type(a))
print("shape: %s" %a.shape)           
print(a[0], a[1], a[2])  
a[0] = 5                  
print(a)
a = np.zeros((2,2))   
print("All zeros matrix:\n  %s" %a)              
                    

b = np.ones((1,2))    
print("\nAll ones matrix:\n  %s" %b)              

d = np.eye(2)        
print("\n identity matrix: \n%s"%d)              
                    

e = np.random.random((2,2))  
print("\n random matrix: \n%s"%e)

type: <class 'numpy.ndarray'>
shape: 3
5 6 7
[5 6 7]
All zeros matrix:
  [[0. 0.]
 [0. 0.]]

All ones matrix:
  [[1. 1.]]

 identity matrix: 
[[1. 0.]
 [0. 1.]]

 random matrix: 
[[0.2394039  0.35878291]
 [0.67513405 0.86445199]]


in the observation book, it starts from here only.

In [ ]:
#vectorized sum
print("Vectorized sum example\n")
x = np.array([[1,2],[3,4]])
print("x:\n %s" %x)
print("sum: %s"%np.sum(x))  # Compute sum of all elements; prints "10"
print("sum axis = 0: %s" %np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(" sum axis = 1: %s" %np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


#matrix dot product
a = np.arange(10000)
b = np.arange(10000)

dp = np.dot(a,b)

print("Dot product: %s\n" %dp)

#outer product
op = np.outer(a,b)
print("\n Outer product: %s\n" %op)

#elementwise product

ep = np.multiply(a, b)

print("\n Element Wise product: %s \n" %ep)

Vectorized sum example

x:
 [[1 2]
 [3 4]]
sum: 10
sum axis = 0: [4 6]
 sum axis = 1: [3 7]
Dot product: 333283335000


 Outer product: [[       0        0        0 ...        0        0        0]
 [       0        1        2 ...     9997     9998     9999]
 [       0        2        4 ...    19994    19996    19998]
 ...
 [       0     9997    19994 ... 99940009 99950006 99960003]
 [       0     9998    19996 ... 99950006 99960004 99970002]
 [       0     9999    19998 ... 99960003 99970002 99980001]]


 Element Wise product: [       0        1        4 ... 99940009 99960004 99980001] 



In [13]:
#elementwise product

ep = np.multiply(a, b)

print("\n Element Wise product: %s \n" %ep)


 Element Wise product: [       0        1        4 ... 99940009 99960004 99980001] 



In [12]:
#outer product
op = np.outer(a,b)
print("\n Outer product: %s\n" %op)


 Outer product: [[       0        0        0 ...        0        0        0]
 [       0        1        2 ...     9997     9998     9999]
 [       0        2        4 ...    19994    19996    19998]
 ...
 [       0     9997    19994 ... 99940009 99950006 99960003]
 [       0     9998    19996 ... 99950006 99960004 99970002]
 [       0     9999    19998 ... 99960003 99970002 99980001]]



In [11]:
a = np.arange(10000)
b = np.arange(10000)

dp = np.dot(a,b)

print("Dot product: %s\n" %dp)

Dot product: 333283335000



In [10]:
x = np.array([[1,2,5,9],[3,4,8,6]])
print("x:\n %s" %x)
print("sum: %s"%np.sum(x))  # Compute sum of all elements; prints "10"
print("sum axis = 0: %s" %np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(" sum axis = 1: %s" %np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


x:
 [[1 2 5 9]
 [3 4 8 6]]
sum: 38
sum axis = 0: [ 4  6 13 15]
 sum axis = 1: [17 21]


(b) Matrix transformation

In [15]:
import numpy as np

x = np.array([[1,2], [3,4]])
print("Original x: \n%s " %x)    # Prints "[[1 2]
            #          [3 4]]"
print("\nTranspose of x: \n%s" %x.T)  # Prints "[[1 3]
            #          [2 4]]"

Original x: 
[[1 2]
 [3 4]] 

Transpose of x: 
[[1 3]
 [2 4]]


In [16]:
import numpy as np

x = np.array([[1,2], [3,4]])
print("Original x: \n%s " %x)    # Prints "[[1 2]
            #          [3 4]]"
print("\nTranspose of x: \n%s" %x.T)  # Prints "[[1 3]
            #          [2 4]]"

Original x: 
[[1 2]
 [3 4]] 

Transpose of x: 
[[1 3]
 [2 4]]


(c) SVD using python

Matrix decomposition, also known as matrix factorization, involves describing a given matrix using its constituent elements.

The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations simpler.

A = U . Sigma . V^T

Where A is the real m x n matrix that we wish to decompose, U is an m x m matrix, Sigma (often represented by the uppercase Greek letter Sigma) is an m x n diagonal matrix, and V^T is the  transpose of an n x n matrix where T is a superscript.


In [14]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print("A: \n%s" %A)
# SVD
U, s, VT = svd(A)
print("\nU: \n%s" %U)
print("\ns: \n %s" %s)
print("\nV^T: \n %s" %VT)

A: 
[[1 2]
 [3 4]
 [5 6]]

U: 
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

s: 
 [9.52551809 0.51430058]

V^T: 
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
